# Render Deployment Configuration
# This file is used by Render to deploy your application

version: 1

services:
  - type: web
    name: vozila
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT source:app --workers 1 --threads 2 --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
